version: '3.8'
services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - GATEWAY_SERVER_PORT=9090

  server:
    build: .
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=password

  db:
    image: postgres
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=password